openapi: 3.1.0
info:
  title: Blob Storage API
  version: 1.0.0
  description: |
    The Blob Storage API allows you to upload or download files from Leanda.
    For example, you can upload a MOL file, and then download the processed result.
    
    **Endpoints:**
    * POST api/blobs/{bucket} - Upload file(s)
    * GET api/blobs/{bucket}/{id} - Download a file
    * DELETE api/blobs/{bucket}/{id} - Delete a file
    * GET api/blobs/{bucket}/{id}/info - Get file metadata
    * GET api/version - Get API version

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.leanda.io
    description: Production server

tags:
  - name: Blobs
    description: Blob storage operations
  - name: Version
    description: API version information

paths:
  /api/blobs/{bucket}:
    post:
      tags:
        - Blobs
      summary: Upload blob(s)
      description: |
        Upload one or more files via multipart/form-data. Each file will be stored
        and a BlobLoaded event will be published. Returns an array of uploaded blob IDs.
      operationId: uploadBlob
      security:
        - BearerAuth: []
      parameters:
        - name: bucket
          in: path
          required: true
          description: Storage bucket identifier (typically user ID)
          schema:
            type: string
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: File to upload (can be multiple files)
                metadata:
                  type: object
                  description: Optional metadata key-value pairs
                  additionalProperties:
                    type: string
            encoding:
              file:
                contentType: application/octet-stream
      responses:
        '200':
          description: Files uploaded successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uuid
                example: ["550e8400-e29b-41d4-a716-446655440000", "660e8400-e29b-41d4-a716-446655440001"]
        '400':
          description: Bad request (invalid content type or missing file)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      tags:
        - Blobs
      summary: Download blob
      description: |
        Download a file by its blob ID. The file will be streamed as binary data.
        Use the content-disposition query parameter to control how the file is delivered.
      operationId: downloadBlob
      security:
        - BearerAuth: []
      parameters:
        - name: bucket
          in: path
          required: true
          description: Storage bucket identifier
          schema:
            type: string
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: id
          in: path
          required: true
          description: Blob identifier (UUID)
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: content-disposition
          in: query
          required: false
          description: Content disposition type
          schema:
            type: string
            enum: [inline, attachment]
            default: inline
            example: inline
      responses:
        '200':
          description: File downloaded successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
          headers:
            Content-Disposition:
              description: Content disposition header
              schema:
                type: string
                example: 'inline; filename="example.mol"'
            Content-Type:
              description: MIME type of the file
              schema:
                type: string
                example: "chemical/x-mdl-molfile"
        '404':
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/blobs/{bucket}/{id}:
    delete:
      tags:
        - Blobs
      summary: Delete blob
      description: |
        Delete a blob by its ID. Note that this only deletes the blob storage entry,
        not the associated file record in the system.
      operationId: deleteBlob
      security:
        - BearerAuth: []
      parameters:
        - name: bucket
          in: path
          required: true
          description: Storage bucket identifier
          schema:
            type: string
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: id
          in: path
          required: true
          description: Blob identifier (UUID)
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '204':
          description: Blob deleted successfully
        '404':
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/blobs/{bucket}/{id}/info:
    get:
      tags:
        - Blobs
      summary: Get blob metadata
      description: |
        Retrieve metadata information about a blob, including file name, size,
        content type, MD5 checksum, upload date, and custom metadata.
      operationId: getBlobInfo
      security:
        - BearerAuth: []
      parameters:
        - name: bucket
          in: path
          required: true
          description: Storage bucket identifier
          schema:
            type: string
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: id
          in: path
          required: true
          description: Blob identifier (UUID)
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: Blob metadata retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlobInfo'
        '404':
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/version:
    get:
      tags:
        - Version
      summary: Get API version
      description: Returns the current version of the Blob Storage API
      operationId: getVersion
      responses:
        '200':
          description: API version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Keycloak authentication

  schemas:
    BlobInfo:
      type: object
      required:
        - id
        - fileName
        - contentType
        - length
        - md5
        - uploadDateTime
      properties:
        id:
          type: string
          format: uuid
          description: Blob identifier
          example: "550e8400-e29b-41d4-a716-446655440000"
        fileName:
          type: string
          description: Original file name
          example: "molecule.mol"
        contentType:
          type: string
          description: MIME type of the file
          example: "chemical/x-mdl-molfile"
        length:
          type: integer
          format: int64
          description: File size in bytes
          example: 1024
        md5:
          type: string
          description: MD5 checksum of the file
          example: "5d41402abc4b2a76b9719d911017c592"
        uploadDateTime:
          type: string
          format: date-time
          description: Upload timestamp (ISO 8601)
          example: "2025-01-15T10:30:00Z"
        metadata:
          type: object
          description: Custom metadata key-value pairs
          additionalProperties:
            type: object
          example:
            source: "upload"
            category: "chemical"

    VersionInfo:
      type: object
      required:
        - version
        - apiVersion
      properties:
        version:
          type: string
          description: Service version
          example: "2.0.0"
        apiVersion:
          type: string
          description: API version
          example: "1.0.0"
        buildDate:
          type: string
          format: date-time
          description: Build timestamp
          example: "2025-01-15T10:00:00Z"

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: "File not found"
        code:
          type: string
          description: Error code
          example: "BLOB_NOT_FOUND"
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
          example: "2025-01-15T10:30:00Z"

