#!/bin/bash

# PR Creation Script for Autonomous Testing
# Creates a PR with test fixes

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() {
    echo -e "${BLUE}[PR CREATOR]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[PR CREATOR]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[PR CREATOR]${NC} $1"
}

# Parse arguments
RUN_ID="${1:-}"
PR_DESCRIPTION_FILE="${2:-}"

if [ -z "$RUN_ID" ]; then
    print_warn "Usage: qa-create-pr.sh <run-id> [pr-description-file]"
    exit 1
fi

cd "$REPO_ROOT"

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    print_warn "Not a git repository. Skipping PR creation."
    exit 0
fi

# Check for changes
if git diff --quiet && git diff --cached --quiet; then
    print_warn "No changes to commit. Skipping PR creation."
    exit 0
fi

# Get current branch
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
BASE_BRANCH="${BASE_BRANCH:-main}"

# Create branch name
BRANCH_NAME="qa-auto-fix-${RUN_ID}"

print_info "Creating PR for run: $RUN_ID"
print_info "Branch: $BRANCH_NAME"
print_info "Base: $BASE_BRANCH"

# Check if branch already exists
if git show-ref --verify --quiet refs/heads/"$BRANCH_NAME"; then
    print_warn "Branch $BRANCH_NAME already exists. Using existing branch."
    git checkout "$BRANCH_NAME"
else
    # Create new branch
    git checkout -b "$BRANCH_NAME" "$BASE_BRANCH" 2>/dev/null || {
        # If base branch doesn't exist, create from current
        git checkout -b "$BRANCH_NAME"
    }
fi

# Stage all changes
git add -A

# Create commit
COMMIT_MSG="[QA-Auto] Fix test failures from run $RUN_ID

This PR contains automated fixes for test failures identified in autonomous test run $RUN_ID.

Generated by QA-Cloud autonomous testing agent."

if [ -n "$PR_DESCRIPTION_FILE" ] && [ -f "$PR_DESCRIPTION_FILE" ]; then
    # Append PR description to commit message
    COMMIT_MSG="$COMMIT_MSG

$(cat "$PR_DESCRIPTION_FILE")"
fi

git commit -m "$COMMIT_MSG" || {
    print_warn "No changes to commit"
    exit 0
}

# Push branch (if remote exists)
if git remote | grep -q origin; then
    print_info "Pushing branch to origin..."
    git push -u origin "$BRANCH_NAME" 2>/dev/null || {
        print_warn "Failed to push branch. PR will need to be created manually."
        print_info "Branch created locally: $BRANCH_NAME"
        exit 0
    }
    
    # Try to create PR using GitHub CLI if available
    if command -v gh > /dev/null 2>&1; then
        print_info "Creating PR using GitHub CLI..."
        
        PR_TITLE="[QA-Auto] Fix test failures - Run $RUN_ID"
        PR_BODY=""
        
        if [ -n "$PR_DESCRIPTION_FILE" ] && [ -f "$PR_DESCRIPTION_FILE" ]; then
            PR_BODY=$(cat "$PR_DESCRIPTION_FILE")
        else
            PR_BODY="Automated fixes for test failures identified in autonomous test run $RUN_ID."
        fi
        
        gh pr create \
            --title "$PR_TITLE" \
            --body "$PR_BODY" \
            --base "$BASE_BRANCH" \
            --head "$BRANCH_NAME" \
            --label "automated,testing" 2>/dev/null || {
            print_warn "Failed to create PR via GitHub CLI"
            print_info "PR can be created manually at: https://github.com/$(git remote get-url origin | sed 's/.*github.com[:/]\(.*\)\.git/\1/')/compare/$BASE_BRANCH...$BRANCH_NAME"
        }
    else
        print_info "GitHub CLI not available. Create PR manually:"
        print_info "  https://github.com/$(git remote get-url origin | sed 's/.*github.com[:/]\(.*\)\.git/\1/')/compare/$BASE_BRANCH...$BRANCH_NAME"
    fi
else
    print_warn "No remote repository configured. Branch created locally: $BRANCH_NAME"
fi

print_success "PR creation process complete"
print_info "Branch: $BRANCH_NAME"

